# Site settings
title: 5srd
baseurl: ""
url: "http://5srd.com"

exclude:
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/bootstrap/docs

keep_files:
  - vendor

permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: ogl-notice
  - scope:
      path: ""
      type: classes
    values:
      layout: class
  - scope:
      path: ""
      type: equipment
    values:
      layout: equipment
  - scope:
      path: ""
      type: languages
    values:
      layout: language
  - scope:
      path: ""
      type: magic-items
    values:
      layout: magic-item
  - scope:
      path: ""
      type: monsters
    values:
      layout: monster
  - scope:
      path: ""
      type: poisons
    values:
      layout: poison
  - scope:
      path: ""
      type: spells
    values:
      layout: spell
  - scope:
      path: ""
      type: subclasses
    values:
      layout: subclass

collections:
  animals:
    permalink: /:collection/:title/
    output: true
  backgrounds:
    permalink: /:collection/:title/
    output: true
  feats:
    permalink: /:collection/:title/
    output: true
  classes:
    permalink: /:collection/:title/
    output: true
  diseases:
    permalink: /:collection/:title/
    output: true
  equipment:
    permalink: /:collection/:title/
    output: true
  languages:
    permalink: /:collection/:title/
    output: true
  magic-items:
    permalink: /:collection/:title/
    output: true
  monsters:
    permalink: /:collection/:title/
    output: true
  npcs:
    permalink: /:collection/:title/
    output: true
  poisons:
    permalink: /:collection/:title/
    output: true
  races:
    permalink: /:collection/:title/
    output: true
  spells:
    permalink: /:collection/:title/
    output: true
  subclasses:
    permalink: /subclasses/:title/
    output: true
  traps:
    permalink: /:collection/:title/
    output: true
